version: '3'
services:
  ping-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
